# Generated by Django 3.2 on 2021-05-02 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='trapper.activity'),
        ),
    ]
